version: "3.8"

services:
  tiktok-downloader:
    build: .
    container_name: tiktok-downloader
    ports:
      - "5000:5000"
    volumes:
      - /mnt/media/learn:/mnt/media/learn
    restart: always
